name: DotmanBankingExpansion
version: 1.0.0
main: com.herzchen.dotmanbankingexpansion.DotmanBankingExpansion
api-version: 1.20
author: Herzchen
commands:
  dbankreload:
    description: Reload plugin configuration