name: DotmanBankingExpansion
version: 1.0.0
main: com.herzchen.dotmanbankingexpansion.DotmanBankingExpansion
api-version: 1.20
author: Herzchen
commands:
  dbe:
    description: Main command for Dotman Banking Expansion
    usage: /dbe [reload|streakinfo|streak|help]
    aliases: [dotmanbanking]
permissions:
  dbe.admin:
    description: Allows access to admin commands
    default: op